version: '3.8'

services:
  db:
    image: mysql:8.1
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: streaming
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysqlstorage:/var/lib/mysql
    ports:
      - '${PORT}:3306'
volumes:
  mysqlstorage: